defaults:
# select between "gilon_activity","microsoft_activity_new","squid_game","fingergesture", "EMOPain"
  - task: SpokenArabicDigits
# select between "shufflenet", "simplevit", "mlpmixer", "resnet9"
  - model: shufflenet
  - channelattention: depthwise
  # select between opl or orthoregularizer
  - loss: orthoregularizer
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# select between "lightning_model_reg_baseline", "lightning_model_opl_recbam", 
lightning_model: 'lightning_model_opl_recbam'
server_name: 'cocacola'

exp_num: 9998
seed: 42
gpu_id: 0

fast_dev_run: False 
limit_train_batches: 1.0
limit_val_batches: 1.0


predict:
  checkpoint_path: 'checkpoints/2023-02-08_13:13:08/shufflenet_epoch=05.ckpt'
  limit_predict_batches: 1
  predict_total: 10
  dropout_rate: 0.2
  pred_save_path: outputs/${task.task_name}/EXP${exp_num}/

dataset:
  batch_size: 256
  num_workers: 4

image_encoding: rp

# Features related
remove_feature: False # remove i-th feature. if -1, do not remove anythin
# There are two ways to drop features, either as a input dictionary or manually
remove_feature_file_name: none  # the name of the dictionary file should be given
remove_feature_file_key: -1 # the key of the dictionary
remove_feature_idx_lists:
  - 0
add_random_channel_idx: False
random_channel_type: white_noise  # white_noise, gp, sine


logger:
  project_name: TEAMDEMA/recbamteam
  name: "${task.task_name}_${model.model_name}_EXP${exp_num}"
  api_key: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJiMDFkM2MzNi1iYWFlLTQ4MTUtOGYxYS02NmIzM2NmNWNiZGEifQ==


save_output_path: outputs/${task.task_name}/EXP${exp_num}
save_classwise_attention_path: outputs/${task.task_name}/classwise_attention/
save_global_attention_path: outputs/${task.task_name}/global_attention/
hydra:
  run:
    dir: ${save_output_path}